# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: ci

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  GO_VERSION: 1.17

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

      - name: test
        run: go test -v ./...

  release:
    name: release  
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.ref, 'main') }}
    needs:
      - "lint"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: ./build.sh
        env:
          # version spec is the path to the variable that will be populated with the build version
          GH_VERSION_SPEC: github.com/chelnak/gh-environments/cmd.version
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
