# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - run: ./build.sh
        env:
          # version spec is the path to the variable that will be populated with the build version
          GH_VERSION_SPEC: github.com/chelnak/gh-environments/cmd.version
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
